security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

        App\Entity\Client :
            algorithm : auto

        App\Entity\Technicien :
            algorithm : auto
    
    providers:
        users_in_memory : { memory : null }   
        
        app_technicien_provider:
            entity:
                class: App\Entity\Technicien
                property: username

        app_client_provider:
            entity:
                class: App\Entity\Client
                property: username

        chain_provider:
            chain :
                providers : [ app_technicien_provider, app_client_provider ]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            form_login: ~
            provider: chain_provider
            custom_authenticator :
                - App\Security\AppAuthenticator
            entry_point : form_login

            logout:
                path: app_logout
                target : app_login
                invalidate_session : true    
            
    role_hierarchy :
        ROLE_CLIENT : ROLE_USER
        ROLE_ADMIN : ROLE_TECHNICIEN
        ROLE_SUPER_ADMIN : [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    access_control:
        - { path : ^/login, roles : PUBLIC_ACCESS }
        - { path : ^/ct, roles : PUBLIC_ACCESS }
        - { path : ^/moto, roles : ROLE_CLIENT }
        - { path: ^/client, roles: ROLE_CLIENT }
        - { path: ^/technicien, roles: ROLE_TECHNICIEN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon

 # client_secure_area :
        #     pattern : ^/clients
        #     provider : app_client_provider
        #     form_login :
        #         login_path : client_login
        #         check_path : client_login
        #         default_target_path : client_home
        #         username_parameter : login[username]
        #         password_parameter : login[password]
        #         enable_csrf : true
        #     logout :
        #         path : app_client_logout
        #         # where to redirect after logout
        #         target : client_login
        #         invalidate_session : true
        #         # configuring the maximum login attemps (per minute)
        #     # login_throttling :
        #     #     max_attempts : 3
        #     custom_authenticator : App\Security\AppClientAuthenticator
        #     entry_point : form_login

        #     remember_me :
        #         secret : '%kernel.secret%'
        #         lifetime : 60
        #         path : /
        #         always_remember_me : true
           


        # technicien_secure_area :
        #     pattern : ^/technicien
        #     provider : app_technicien_provider
        #     form_login :
        #         login_path : technicien_login
        #         check_path : technicien_login
        #         default_target_path : technicien_home
        #         username_parameter : login[username]
        #         password_parameter : login[password]
        #         enable_csrf : true
        #     logout :
        #         path : app_technicien_logout
        #         target : technicien_login
        #         invalidate_session : true
        #     login_throttling :
        #         max_attempts : 3
        #     custom_authenticator : App\Security\AppTechnicienAuthenticator
        #     entry_point : form_login

        #     remember_me :
        #         secret : '%kernel.secret%'
        #         lifetime : 60
        #         path : /
        #         always_remember_me : true